// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXVBsy23PYeghX8bGjIT45qrn8HuB-r3I',
    appId: '1:155405817003:web:915fc6721ff433511a93ee',
    messagingSenderId: '155405817003',
    projectId: 'intagram-cool-project',
    authDomain: 'intagram-cool-project.firebaseapp.com',
    storageBucket: 'intagram-cool-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCF8h-Yr6jGwymfPwA3rlRb1fA-fijT2o',
    appId: '1:155405817003:android:eec90fa39d43f6161a93ee',
    messagingSenderId: '155405817003',
    projectId: 'intagram-cool-project',
    storageBucket: 'intagram-cool-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5lBIw5i7EPk6QwurSQAZIRSBtwRmwV90',
    appId: '1:155405817003:ios:35f73b40118489ae1a93ee',
    messagingSenderId: '155405817003',
    projectId: 'intagram-cool-project',
    storageBucket: 'intagram-cool-project.appspot.com',
    iosClientId: '155405817003-hahlobdl9v10bk1gmoqtksccdaedd8no.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5lBIw5i7EPk6QwurSQAZIRSBtwRmwV90',
    appId: '1:155405817003:ios:35f73b40118489ae1a93ee',
    messagingSenderId: '155405817003',
    projectId: 'intagram-cool-project',
    storageBucket: 'intagram-cool-project.appspot.com',
    iosClientId: '155405817003-hahlobdl9v10bk1gmoqtksccdaedd8no.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramClone',
  );
}
